storage:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    database: chat
    username: root
    password: password

pubsub:
  type: redis
  redis:
    host: localhost
    port: 6379

filters:
  webpurify-api-key: abc123
