messaging:
  redis:
    use: true
    address: localhost

player-storage:
  mysql:
    use: true
    address: localhost
    port: 3306
    database: minecraft
    username: root
    password: password

channels:
  local:
    type: default
  private-message:
    storage:
      redis:
        use: true
        address: localhost

chat-filters:
  profanity:
    webpurify-key: abc123

logging:
  console:
    use: true
  mysql:
    use: true
    address: localhost
    port: 3306
    database: minecraft
    username: root
    password: password
    