storage:
  mysql:
    host: localhost
    port: 3306
    database: chat
    username: root
    password: password
racialslurs:
  - nigger
  - nigga
  - nibba
  - nigqa
  - niqqa
  - niglet
  - chink
  - kike
badwords:
  - anal
  - anus
  - arse
  - ass
  - ballsack
  - balls
  - bastard
  - bitch
  - biatch
  - blowjob
  - blow job
  - boner
  - boob
  - buttplug
  - clitoris
  - cock
  - coon
  - cunt
  - cum
  - cumming
  - cums
  - damn
  - dick
  - dildo
  - dyke
  - fag
  - fagget
  - faggot
  - feck
  - fellate
  - fellatio
  - felching
  - fuck
  - fucc
  - fuk
  - phuck
  - fudgepacker
  - fudge packer
  - flange
  - Goddamn
  - God damn
  - hell
  - jizz
  - knob end
  - labia
  - lmao
  - lmfao
  - penis
  - piss
  - pube
  - pussy
  - queer
  - scrotum
  - sex
  - shit
  - slut
  - sperm
  - tit
  - tosser
  - twat
  - vagina
  - wank
  - whore
  - wtf
