main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
author: royalkingkb
depend: [ Vault ]
softdepend: [ PlotSquared, Towny, CinemaDisplays ]
commands:
  list:
  seen:
  friend:
  mail:
  block:
  unblock:
  nickname:
  nicknamereset:
  namecolor:
    permission: ruinscraft.command.namecolor
  directmessage:
    aliases: [ dm, pm, m, msg, message, whisper, w ]
  reply:
    aliases: [ r ]
