main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
author: royalkingkb
depend: [ Vault ]
softdepend: [ PlotSquared, Towny ]
commands:
  list:
  seen:
  friend:
  mail:
  block:
  unblock:
