name: ${name}
version: ${version}
main: ${mainClass}

api-version: 1.13

depend: [ruinscraft-player-status, Vault]
softdepend: [Towny, mcMMO]

commands:
  ignore:
    description: Ignore or unignore a player
  clearchat:
    description: Clear the chat
    permission: ruinscraft.command.clearchat
  nickname:
    description: Set your nickname (seen in local chat)
    aliases: [rpname, nick]
  nicknamereset:
    description: Reset your nickname
    aliases: [rpnamereset, nickreset]
  chat:
    description: Manage chat settings
  chatspy:
    description: Manage chat spy settings
    permission: ruinscraft.command.chatspy
  me:
    description: Do something as yourself
