name: ${name}
version: ${version}
main: ${mainClass}

depend: [ruinscraft-player-status, Vault]

commands:
  ignore:
    description: Ignore or unignore a player
  clearchat:
    description: Clear the chat
    permission: ruinscraft.command.clearchat
  nickname:
    description: Set your nickname (seen in local chat)
    aliases: [rpname, nick]
  nicknamereset:
    description: Reset your nickname
    aliases: [rpnamereset, nickreset]
  chat:
    description: Manage chat settings
  chatspy:
    description: Manage chat spy settings
    permission: ruinscraft.command.chatspy
