storage:
  type: mysql
  mysql:
    host: db
    port: 3306
    database: chat
    username: root
    password: password

message-broker:
  type: redis
  redis:
    host: pubsub
    port: 6379

filters:
  webpurify-api-key: abc123
